language: php

php:
  - 5.3
  - 5.4

before_install:
 - composer install
 - wget http://cs.sensiolabs.org/get/php-cs-fixer.phar

script:
 - cd ./tests/ && phpunit
 - output=$(php php-cs-fixer.phar fix -v --dry-run --level=psr2 .); if [[ $output ]]; then while read -r line; do echo -e "\e[00;31m$line\e[00m"; done <<< "$output"; false; fi;

notifications:
  irc: "irc.freenode.org#zftalk.dev"
  email: false
